#!/bin/sh

echo
count=0

echo "Looking for outstanding merge conflicts"
for f in `git diff HEAD --name-only --diff-filter=M`; do
    if [ -f $f ]; then
        if grep -Fxq "<<<<<<<" $f; then
            echo "    $(tput setaf 1)$f$(tput sgr0)"
            ((count += 1))
        fi
    fi
done

echo
echo "Summary:"
if [ $count != 0 ]; then
    echo "    $(tput setaf 1)$count$(tput sgr0) files conflict, please resolve conflicts."
    exit 1;
else
    echo "    $(tput setaf 2)No conflicts, continuing with commit.$(tput sgr0)"
    echo
fi
