// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2.proto

package c2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2Request_Command int32

const (
	C2Request_NEW_CLIENT          C2Request_Command = 0
	C2Request_REMOVE_CLIENT       C2Request_Command = 1
	C2Request_NEW_TOPIC_CLIENT    C2Request_Command = 2
	C2Request_REMOVE_TOPIC_CLIENT C2Request_Command = 3
	C2Request_RESET_CLIENT        C2Request_Command = 4
	C2Request_NEW_TOPIC           C2Request_Command = 5
	C2Request_REMOVE_TOPIC        C2Request_Command = 6
	C2Request_NEW_CLIENT_KEY      C2Request_Command = 7
	C2Request_SEND_MESSAGE        C2Request_Command = 8
	C2Request_GET_CLIENTS         C2Request_Command = 9
	C2Request_GET_TOPICS          C2Request_Command = 10
)

var C2Request_Command_name = map[int32]string{
	0:  "NEW_CLIENT",
	1:  "REMOVE_CLIENT",
	2:  "NEW_TOPIC_CLIENT",
	3:  "REMOVE_TOPIC_CLIENT",
	4:  "RESET_CLIENT",
	5:  "NEW_TOPIC",
	6:  "REMOVE_TOPIC",
	7:  "NEW_CLIENT_KEY",
	8:  "SEND_MESSAGE",
	9:  "GET_CLIENTS",
	10: "GET_TOPICS",
}
var C2Request_Command_value = map[string]int32{
	"NEW_CLIENT":          0,
	"REMOVE_CLIENT":       1,
	"NEW_TOPIC_CLIENT":    2,
	"REMOVE_TOPIC_CLIENT": 3,
	"RESET_CLIENT":        4,
	"NEW_TOPIC":           5,
	"REMOVE_TOPIC":        6,
	"NEW_CLIENT_KEY":      7,
	"SEND_MESSAGE":        8,
	"GET_CLIENTS":         9,
	"GET_TOPICS":          10,
}

func (x C2Request_Command) String() string {
	return proto.EnumName(C2Request_Command_name, int32(x))
}
func (C2Request_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2_88aa747daeadc023, []int{0, 0}
}

type C2Request struct {
	Command              C2Request_Command `protobuf:"varint,1,opt,name=command,proto3,enum=c2.C2Request_Command" json:"command,omitempty"`
	Id                   []byte            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Key                  []byte            `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Topic                string            `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Msg                  string            `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *C2Request) Reset()         { *m = C2Request{} }
func (m *C2Request) String() string { return proto.CompactTextString(m) }
func (*C2Request) ProtoMessage()    {}
func (*C2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2_88aa747daeadc023, []int{0}
}
func (m *C2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2Request.Unmarshal(m, b)
}
func (m *C2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2Request.Marshal(b, m, deterministic)
}
func (dst *C2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2Request.Merge(dst, src)
}
func (m *C2Request) XXX_Size() int {
	return xxx_messageInfo_C2Request.Size(m)
}
func (m *C2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_C2Request.DiscardUnknown(m)
}

var xxx_messageInfo_C2Request proto.InternalMessageInfo

func (m *C2Request) GetCommand() C2Request_Command {
	if m != nil {
		return m.Command
	}
	return C2Request_NEW_CLIENT
}

func (m *C2Request) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *C2Request) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *C2Request) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *C2Request) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type C2Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Ids                  []string `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	Topics               []string `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2Response) Reset()         { *m = C2Response{} }
func (m *C2Response) String() string { return proto.CompactTextString(m) }
func (*C2Response) ProtoMessage()    {}
func (*C2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2_88aa747daeadc023, []int{1}
}
func (m *C2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2Response.Unmarshal(m, b)
}
func (m *C2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2Response.Marshal(b, m, deterministic)
}
func (dst *C2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2Response.Merge(dst, src)
}
func (m *C2Response) XXX_Size() int {
	return xxx_messageInfo_C2Response.Size(m)
}
func (m *C2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_C2Response.DiscardUnknown(m)
}

var xxx_messageInfo_C2Response proto.InternalMessageInfo

func (m *C2Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *C2Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *C2Response) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *C2Response) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*C2Request)(nil), "c2.C2Request")
	proto.RegisterType((*C2Response)(nil), "c2.C2Response")
	proto.RegisterEnum("c2.C2Request_Command", C2Request_Command_name, C2Request_Command_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// C2Client is the client API for C2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type C2Client interface {
	C2Command(ctx context.Context, in *C2Request, opts ...grpc.CallOption) (*C2Response, error)
}

type c2Client struct {
	cc *grpc.ClientConn
}

func NewC2Client(cc *grpc.ClientConn) C2Client {
	return &c2Client{cc}
}

func (c *c2Client) C2Command(ctx context.Context, in *C2Request, opts ...grpc.CallOption) (*C2Response, error) {
	out := new(C2Response)
	err := c.cc.Invoke(ctx, "/c2.C2/C2Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// C2Server is the server API for C2 service.
type C2Server interface {
	C2Command(context.Context, *C2Request) (*C2Response, error)
}

func RegisterC2Server(s *grpc.Server, srv C2Server) {
	s.RegisterService(&_C2_serviceDesc, srv)
}

func _C2_C2Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).C2Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/c2.C2/C2Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).C2Command(ctx, req.(*C2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _C2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "c2.C2",
	HandlerType: (*C2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "C2Command",
			Handler:    _C2_C2Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "c2.proto",
}

func init() { proto.RegisterFile("c2.proto", fileDescriptor_c2_88aa747daeadc023) }

var fileDescriptor_c2_88aa747daeadc023 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x41, 0x6f, 0xe2, 0x30,
	0x10, 0x85, 0x49, 0x02, 0x84, 0xcc, 0x42, 0xd6, 0x3b, 0xcb, 0x6e, 0xad, 0x9e, 0xa2, 0x9c, 0x38,
	0x54, 0xa9, 0xe4, 0xfe, 0x82, 0x2a, 0xb5, 0x10, 0x6a, 0x81, 0xca, 0x41, 0xad, 0x7a, 0x42, 0xc5,
	0x89, 0xaa, 0xa8, 0x82, 0x50, 0x0c, 0x87, 0xfe, 0xd0, 0x5e, 0xfb, 0x5b, 0x2a, 0x3b, 0x38, 0x88,
	0xdb, 0xbc, 0x6f, 0x5e, 0x9e, 0x46, 0xcf, 0x81, 0x9e, 0x64, 0xc9, 0x76, 0x57, 0xed, 0x2b, 0x74,
	0x25, 0x8b, 0xbf, 0x5d, 0x08, 0x52, 0x26, 0x8a, 0x8f, 0x43, 0xa1, 0xf6, 0x78, 0x0d, 0xbe, 0xac,
	0xd6, 0xeb, 0xd7, 0x4d, 0x4e, 0x9d, 0xc8, 0x19, 0x85, 0xec, 0x5f, 0x22, 0x59, 0xd2, 0xec, 0x93,
	0xb4, 0x5e, 0x0a, 0xeb, 0xc2, 0x10, 0xdc, 0x32, 0xa7, 0x6e, 0xe4, 0x8c, 0xfa, 0xc2, 0x2d, 0x73,
	0x24, 0xe0, 0xbd, 0x17, 0x9f, 0xd4, 0x33, 0x40, 0x8f, 0x38, 0x84, 0xce, 0xbe, 0xda, 0x96, 0x92,
	0xb6, 0x23, 0x67, 0x14, 0x88, 0x5a, 0x68, 0xdf, 0x5a, 0xbd, 0xd1, 0x8e, 0x61, 0x7a, 0x8c, 0xbf,
	0x1c, 0xf0, 0xd3, 0x26, 0x15, 0x66, 0xfc, 0x79, 0x99, 0x3e, 0x4c, 0xf8, 0x6c, 0x41, 0x5a, 0xf8,
	0x07, 0x06, 0x82, 0x4f, 0xe7, 0x4f, 0xdc, 0x22, 0x07, 0x87, 0x40, 0xb4, 0x65, 0x31, 0x7f, 0x9c,
	0xa4, 0x96, 0xba, 0x78, 0x01, 0x7f, 0x8f, 0xc6, 0xb3, 0x85, 0x87, 0x04, 0xfa, 0x82, 0x67, 0x7c,
	0x61, 0x49, 0x1b, 0x07, 0x10, 0x34, 0x01, 0xa4, 0x53, 0x1b, 0x4e, 0x5f, 0x92, 0x2e, 0x22, 0x84,
	0xa7, 0x23, 0x96, 0xf7, 0xfc, 0x85, 0xf8, 0xda, 0x95, 0xf1, 0xd9, 0xdd, 0x72, 0xca, 0xb3, 0xec,
	0x76, 0xcc, 0x49, 0x0f, 0x7f, 0xc3, 0xaf, 0x71, 0x13, 0x9b, 0x91, 0x40, 0xdf, 0xae, 0x81, 0x49,
	0xc9, 0x08, 0xc4, 0x2b, 0x00, 0xdd, 0x9f, 0xda, 0x56, 0x1b, 0x55, 0x20, 0x05, 0x5f, 0x1d, 0xa4,
	0x2c, 0x94, 0x32, 0x05, 0xf7, 0x84, 0x95, 0xba, 0x91, 0x62, 0xb7, 0x33, 0x55, 0x06, 0x42, 0x8f,
	0x9a, 0x94, 0xb9, 0xa2, 0x5e, 0xe4, 0x69, 0x52, 0xe6, 0x0a, 0xff, 0x43, 0xd7, 0xd4, 0xa7, 0x68,
	0xdb, 0xc0, 0xa3, 0x62, 0x0c, 0xdc, 0x94, 0xe1, 0x95, 0x7e, 0x49, 0x5b, 0xe1, 0xe0, 0xec, 0xe1,
	0x2e, 0x43, 0x2b, 0xeb, 0x3b, 0xe2, 0xd6, 0xaa, 0x6b, 0xfe, 0x81, 0x9b, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd9, 0xfd, 0x40, 0xff, 0x0f, 0x02, 0x00, 0x00,
}
