
CREATE ROLE e4 WITH NOSUPERUSER NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS;


CREATE ROLE e4_c2_test WITH NOSUPERUSER NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS;
ALTER ROLE e4_c2_test WITH ENCRYPTED PASSWORD 'teserakte4';

CREATE DATABASE IF NOT EXISTS e4 WITH OWNER=e4 LC_COLLATE="en_US.UTF-8" LC_CTYPE="en_US.UTF-8" ENCODING=UTF8 TEMPLATE=template0;
\connect e4;
CREATE SCHEMA IF NOT EXISTS e4_c2_test AUTHORIZATION e4_c2_test;

GRANT ALL ON SCHEMA e4_c2_test TO e4;
