// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NewClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientRequest) Reset()         { *m = NewClientRequest{} }
func (m *NewClientRequest) String() string { return proto.CompactTextString(m) }
func (*NewClientRequest) ProtoMessage()    {}
func (*NewClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *NewClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientRequest.Unmarshal(m, b)
}
func (m *NewClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientRequest.Marshal(b, m, deterministic)
}
func (m *NewClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientRequest.Merge(m, src)
}
func (m *NewClientRequest) XXX_Size() int {
	return xxx_messageInfo_NewClientRequest.Size(m)
}
func (m *NewClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientRequest proto.InternalMessageInfo

func (m *NewClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *NewClientRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type NewClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientResponse) Reset()         { *m = NewClientResponse{} }
func (m *NewClientResponse) String() string { return proto.CompactTextString(m) }
func (*NewClientResponse) ProtoMessage()    {}
func (*NewClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *NewClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientResponse.Unmarshal(m, b)
}
func (m *NewClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientResponse.Marshal(b, m, deterministic)
}
func (m *NewClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientResponse.Merge(m, src)
}
func (m *NewClientResponse) XXX_Size() int {
	return xxx_messageInfo_NewClientResponse.Size(m)
}
func (m *NewClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientResponse proto.InternalMessageInfo

type RemoveClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveClientRequest) Reset()         { *m = RemoveClientRequest{} }
func (m *RemoveClientRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveClientRequest) ProtoMessage()    {}
func (*RemoveClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *RemoveClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveClientRequest.Unmarshal(m, b)
}
func (m *RemoveClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveClientRequest.Marshal(b, m, deterministic)
}
func (m *RemoveClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveClientRequest.Merge(m, src)
}
func (m *RemoveClientRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveClientRequest.Size(m)
}
func (m *RemoveClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveClientRequest proto.InternalMessageInfo

func (m *RemoveClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type RemoveClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveClientResponse) Reset()         { *m = RemoveClientResponse{} }
func (m *RemoveClientResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveClientResponse) ProtoMessage()    {}
func (*RemoveClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *RemoveClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveClientResponse.Unmarshal(m, b)
}
func (m *RemoveClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveClientResponse.Marshal(b, m, deterministic)
}
func (m *RemoveClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveClientResponse.Merge(m, src)
}
func (m *RemoveClientResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveClientResponse.Size(m)
}
func (m *RemoveClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveClientResponse proto.InternalMessageInfo

type NewTopicClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTopicClientRequest) Reset()         { *m = NewTopicClientRequest{} }
func (m *NewTopicClientRequest) String() string { return proto.CompactTextString(m) }
func (*NewTopicClientRequest) ProtoMessage()    {}
func (*NewTopicClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *NewTopicClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTopicClientRequest.Unmarshal(m, b)
}
func (m *NewTopicClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTopicClientRequest.Marshal(b, m, deterministic)
}
func (m *NewTopicClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTopicClientRequest.Merge(m, src)
}
func (m *NewTopicClientRequest) XXX_Size() int {
	return xxx_messageInfo_NewTopicClientRequest.Size(m)
}
func (m *NewTopicClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTopicClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTopicClientRequest proto.InternalMessageInfo

func (m *NewTopicClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *NewTopicClientRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type NewTopicClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTopicClientResponse) Reset()         { *m = NewTopicClientResponse{} }
func (m *NewTopicClientResponse) String() string { return proto.CompactTextString(m) }
func (*NewTopicClientResponse) ProtoMessage()    {}
func (*NewTopicClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *NewTopicClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTopicClientResponse.Unmarshal(m, b)
}
func (m *NewTopicClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTopicClientResponse.Marshal(b, m, deterministic)
}
func (m *NewTopicClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTopicClientResponse.Merge(m, src)
}
func (m *NewTopicClientResponse) XXX_Size() int {
	return xxx_messageInfo_NewTopicClientResponse.Size(m)
}
func (m *NewTopicClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTopicClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTopicClientResponse proto.InternalMessageInfo

type RemoveTopicClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTopicClientRequest) Reset()         { *m = RemoveTopicClientRequest{} }
func (m *RemoveTopicClientRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTopicClientRequest) ProtoMessage()    {}
func (*RemoveTopicClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *RemoveTopicClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTopicClientRequest.Unmarshal(m, b)
}
func (m *RemoveTopicClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTopicClientRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTopicClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTopicClientRequest.Merge(m, src)
}
func (m *RemoveTopicClientRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTopicClientRequest.Size(m)
}
func (m *RemoveTopicClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTopicClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTopicClientRequest proto.InternalMessageInfo

func (m *RemoveTopicClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *RemoveTopicClientRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type RemoveTopicClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTopicClientResponse) Reset()         { *m = RemoveTopicClientResponse{} }
func (m *RemoveTopicClientResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTopicClientResponse) ProtoMessage()    {}
func (*RemoveTopicClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *RemoveTopicClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTopicClientResponse.Unmarshal(m, b)
}
func (m *RemoveTopicClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTopicClientResponse.Marshal(b, m, deterministic)
}
func (m *RemoveTopicClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTopicClientResponse.Merge(m, src)
}
func (m *RemoveTopicClientResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveTopicClientResponse.Size(m)
}
func (m *RemoveTopicClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTopicClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTopicClientResponse proto.InternalMessageInfo

type ResetClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetClientRequest) Reset()         { *m = ResetClientRequest{} }
func (m *ResetClientRequest) String() string { return proto.CompactTextString(m) }
func (*ResetClientRequest) ProtoMessage()    {}
func (*ResetClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ResetClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetClientRequest.Unmarshal(m, b)
}
func (m *ResetClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetClientRequest.Marshal(b, m, deterministic)
}
func (m *ResetClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetClientRequest.Merge(m, src)
}
func (m *ResetClientRequest) XXX_Size() int {
	return xxx_messageInfo_ResetClientRequest.Size(m)
}
func (m *ResetClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetClientRequest proto.InternalMessageInfo

func (m *ResetClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type ResetClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetClientResponse) Reset()         { *m = ResetClientResponse{} }
func (m *ResetClientResponse) String() string { return proto.CompactTextString(m) }
func (*ResetClientResponse) ProtoMessage()    {}
func (*ResetClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ResetClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetClientResponse.Unmarshal(m, b)
}
func (m *ResetClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetClientResponse.Marshal(b, m, deterministic)
}
func (m *ResetClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetClientResponse.Merge(m, src)
}
func (m *ResetClientResponse) XXX_Size() int {
	return xxx_messageInfo_ResetClientResponse.Size(m)
}
func (m *ResetClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetClientResponse proto.InternalMessageInfo

type NewTopicRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTopicRequest) Reset()         { *m = NewTopicRequest{} }
func (m *NewTopicRequest) String() string { return proto.CompactTextString(m) }
func (*NewTopicRequest) ProtoMessage()    {}
func (*NewTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *NewTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTopicRequest.Unmarshal(m, b)
}
func (m *NewTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTopicRequest.Marshal(b, m, deterministic)
}
func (m *NewTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTopicRequest.Merge(m, src)
}
func (m *NewTopicRequest) XXX_Size() int {
	return xxx_messageInfo_NewTopicRequest.Size(m)
}
func (m *NewTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTopicRequest proto.InternalMessageInfo

func (m *NewTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type NewTopicResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTopicResponse) Reset()         { *m = NewTopicResponse{} }
func (m *NewTopicResponse) String() string { return proto.CompactTextString(m) }
func (*NewTopicResponse) ProtoMessage()    {}
func (*NewTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *NewTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTopicResponse.Unmarshal(m, b)
}
func (m *NewTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTopicResponse.Marshal(b, m, deterministic)
}
func (m *NewTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTopicResponse.Merge(m, src)
}
func (m *NewTopicResponse) XXX_Size() int {
	return xxx_messageInfo_NewTopicResponse.Size(m)
}
func (m *NewTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTopicResponse proto.InternalMessageInfo

type RemoveTopicRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTopicRequest) Reset()         { *m = RemoveTopicRequest{} }
func (m *RemoveTopicRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTopicRequest) ProtoMessage()    {}
func (*RemoveTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *RemoveTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTopicRequest.Unmarshal(m, b)
}
func (m *RemoveTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTopicRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTopicRequest.Merge(m, src)
}
func (m *RemoveTopicRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTopicRequest.Size(m)
}
func (m *RemoveTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTopicRequest proto.InternalMessageInfo

func (m *RemoveTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type RemoveTopicResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTopicResponse) Reset()         { *m = RemoveTopicResponse{} }
func (m *RemoveTopicResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTopicResponse) ProtoMessage()    {}
func (*RemoveTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *RemoveTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTopicResponse.Unmarshal(m, b)
}
func (m *RemoveTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTopicResponse.Marshal(b, m, deterministic)
}
func (m *RemoveTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTopicResponse.Merge(m, src)
}
func (m *RemoveTopicResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveTopicResponse.Size(m)
}
func (m *RemoveTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTopicResponse proto.InternalMessageInfo

type NewClientKeyRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientKeyRequest) Reset()         { *m = NewClientKeyRequest{} }
func (m *NewClientKeyRequest) String() string { return proto.CompactTextString(m) }
func (*NewClientKeyRequest) ProtoMessage()    {}
func (*NewClientKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *NewClientKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientKeyRequest.Unmarshal(m, b)
}
func (m *NewClientKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientKeyRequest.Marshal(b, m, deterministic)
}
func (m *NewClientKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientKeyRequest.Merge(m, src)
}
func (m *NewClientKeyRequest) XXX_Size() int {
	return xxx_messageInfo_NewClientKeyRequest.Size(m)
}
func (m *NewClientKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientKeyRequest proto.InternalMessageInfo

func (m *NewClientKeyRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type NewClientKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientKeyResponse) Reset()         { *m = NewClientKeyResponse{} }
func (m *NewClientKeyResponse) String() string { return proto.CompactTextString(m) }
func (*NewClientKeyResponse) ProtoMessage()    {}
func (*NewClientKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *NewClientKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientKeyResponse.Unmarshal(m, b)
}
func (m *NewClientKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientKeyResponse.Marshal(b, m, deterministic)
}
func (m *NewClientKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientKeyResponse.Merge(m, src)
}
func (m *NewClientKeyResponse) XXX_Size() int {
	return xxx_messageInfo_NewClientKeyResponse.Size(m)
}
func (m *NewClientKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientKeyResponse proto.InternalMessageInfo

type CountTopicsForClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountTopicsForClientRequest) Reset()         { *m = CountTopicsForClientRequest{} }
func (m *CountTopicsForClientRequest) String() string { return proto.CompactTextString(m) }
func (*CountTopicsForClientRequest) ProtoMessage()    {}
func (*CountTopicsForClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *CountTopicsForClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountTopicsForClientRequest.Unmarshal(m, b)
}
func (m *CountTopicsForClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountTopicsForClientRequest.Marshal(b, m, deterministic)
}
func (m *CountTopicsForClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountTopicsForClientRequest.Merge(m, src)
}
func (m *CountTopicsForClientRequest) XXX_Size() int {
	return xxx_messageInfo_CountTopicsForClientRequest.Size(m)
}
func (m *CountTopicsForClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountTopicsForClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountTopicsForClientRequest proto.InternalMessageInfo

func (m *CountTopicsForClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type CountTopicsForClientResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountTopicsForClientResponse) Reset()         { *m = CountTopicsForClientResponse{} }
func (m *CountTopicsForClientResponse) String() string { return proto.CompactTextString(m) }
func (*CountTopicsForClientResponse) ProtoMessage()    {}
func (*CountTopicsForClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *CountTopicsForClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountTopicsForClientResponse.Unmarshal(m, b)
}
func (m *CountTopicsForClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountTopicsForClientResponse.Marshal(b, m, deterministic)
}
func (m *CountTopicsForClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountTopicsForClientResponse.Merge(m, src)
}
func (m *CountTopicsForClientResponse) XXX_Size() int {
	return xxx_messageInfo_CountTopicsForClientResponse.Size(m)
}
func (m *CountTopicsForClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountTopicsForClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountTopicsForClientResponse proto.InternalMessageInfo

func (m *CountTopicsForClientResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetTopicsForClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsForClientRequest) Reset()         { *m = GetTopicsForClientRequest{} }
func (m *GetTopicsForClientRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicsForClientRequest) ProtoMessage()    {}
func (*GetTopicsForClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *GetTopicsForClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsForClientRequest.Unmarshal(m, b)
}
func (m *GetTopicsForClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsForClientRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicsForClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsForClientRequest.Merge(m, src)
}
func (m *GetTopicsForClientRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicsForClientRequest.Size(m)
}
func (m *GetTopicsForClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsForClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsForClientRequest proto.InternalMessageInfo

func (m *GetTopicsForClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *GetTopicsForClientRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetTopicsForClientRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetTopicsForClientResponse struct {
	Topics               []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsForClientResponse) Reset()         { *m = GetTopicsForClientResponse{} }
func (m *GetTopicsForClientResponse) String() string { return proto.CompactTextString(m) }
func (*GetTopicsForClientResponse) ProtoMessage()    {}
func (*GetTopicsForClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *GetTopicsForClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsForClientResponse.Unmarshal(m, b)
}
func (m *GetTopicsForClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsForClientResponse.Marshal(b, m, deterministic)
}
func (m *GetTopicsForClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsForClientResponse.Merge(m, src)
}
func (m *GetTopicsForClientResponse) XXX_Size() int {
	return xxx_messageInfo_GetTopicsForClientResponse.Size(m)
}
func (m *GetTopicsForClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsForClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsForClientResponse proto.InternalMessageInfo

func (m *GetTopicsForClientResponse) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type CountClientsForTopicRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountClientsForTopicRequest) Reset()         { *m = CountClientsForTopicRequest{} }
func (m *CountClientsForTopicRequest) String() string { return proto.CompactTextString(m) }
func (*CountClientsForTopicRequest) ProtoMessage()    {}
func (*CountClientsForTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *CountClientsForTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountClientsForTopicRequest.Unmarshal(m, b)
}
func (m *CountClientsForTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountClientsForTopicRequest.Marshal(b, m, deterministic)
}
func (m *CountClientsForTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountClientsForTopicRequest.Merge(m, src)
}
func (m *CountClientsForTopicRequest) XXX_Size() int {
	return xxx_messageInfo_CountClientsForTopicRequest.Size(m)
}
func (m *CountClientsForTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountClientsForTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountClientsForTopicRequest proto.InternalMessageInfo

func (m *CountClientsForTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type CountClientsForTopicResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountClientsForTopicResponse) Reset()         { *m = CountClientsForTopicResponse{} }
func (m *CountClientsForTopicResponse) String() string { return proto.CompactTextString(m) }
func (*CountClientsForTopicResponse) ProtoMessage()    {}
func (*CountClientsForTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *CountClientsForTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountClientsForTopicResponse.Unmarshal(m, b)
}
func (m *CountClientsForTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountClientsForTopicResponse.Marshal(b, m, deterministic)
}
func (m *CountClientsForTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountClientsForTopicResponse.Merge(m, src)
}
func (m *CountClientsForTopicResponse) XXX_Size() int {
	return xxx_messageInfo_CountClientsForTopicResponse.Size(m)
}
func (m *CountClientsForTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountClientsForTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountClientsForTopicResponse proto.InternalMessageInfo

func (m *CountClientsForTopicResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetClientsForTopicRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientsForTopicRequest) Reset()         { *m = GetClientsForTopicRequest{} }
func (m *GetClientsForTopicRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientsForTopicRequest) ProtoMessage()    {}
func (*GetClientsForTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *GetClientsForTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsForTopicRequest.Unmarshal(m, b)
}
func (m *GetClientsForTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsForTopicRequest.Marshal(b, m, deterministic)
}
func (m *GetClientsForTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsForTopicRequest.Merge(m, src)
}
func (m *GetClientsForTopicRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientsForTopicRequest.Size(m)
}
func (m *GetClientsForTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsForTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsForTopicRequest proto.InternalMessageInfo

func (m *GetClientsForTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GetClientsForTopicRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetClientsForTopicRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetClientsForTopicResponse struct {
	Clients              []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetClientsForTopicResponse) Reset()         { *m = GetClientsForTopicResponse{} }
func (m *GetClientsForTopicResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientsForTopicResponse) ProtoMessage()    {}
func (*GetClientsForTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *GetClientsForTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsForTopicResponse.Unmarshal(m, b)
}
func (m *GetClientsForTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsForTopicResponse.Marshal(b, m, deterministic)
}
func (m *GetClientsForTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsForTopicResponse.Merge(m, src)
}
func (m *GetClientsForTopicResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientsForTopicResponse.Size(m)
}
func (m *GetClientsForTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsForTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsForTopicResponse proto.InternalMessageInfo

func (m *GetClientsForTopicResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type CountClientsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountClientsRequest) Reset()         { *m = CountClientsRequest{} }
func (m *CountClientsRequest) String() string { return proto.CompactTextString(m) }
func (*CountClientsRequest) ProtoMessage()    {}
func (*CountClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *CountClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountClientsRequest.Unmarshal(m, b)
}
func (m *CountClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountClientsRequest.Marshal(b, m, deterministic)
}
func (m *CountClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountClientsRequest.Merge(m, src)
}
func (m *CountClientsRequest) XXX_Size() int {
	return xxx_messageInfo_CountClientsRequest.Size(m)
}
func (m *CountClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountClientsRequest proto.InternalMessageInfo

type CountClientsResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountClientsResponse) Reset()         { *m = CountClientsResponse{} }
func (m *CountClientsResponse) String() string { return proto.CompactTextString(m) }
func (*CountClientsResponse) ProtoMessage()    {}
func (*CountClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *CountClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountClientsResponse.Unmarshal(m, b)
}
func (m *CountClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountClientsResponse.Marshal(b, m, deterministic)
}
func (m *CountClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountClientsResponse.Merge(m, src)
}
func (m *CountClientsResponse) XXX_Size() int {
	return xxx_messageInfo_CountClientsResponse.Size(m)
}
func (m *CountClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountClientsResponse proto.InternalMessageInfo

func (m *CountClientsResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetClientsRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientsRequest) Reset()         { *m = GetClientsRequest{} }
func (m *GetClientsRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientsRequest) ProtoMessage()    {}
func (*GetClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *GetClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsRequest.Unmarshal(m, b)
}
func (m *GetClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsRequest.Marshal(b, m, deterministic)
}
func (m *GetClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsRequest.Merge(m, src)
}
func (m *GetClientsRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientsRequest.Size(m)
}
func (m *GetClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsRequest proto.InternalMessageInfo

func (m *GetClientsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetClientsRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetClientsResponse struct {
	Clients              []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetClientsResponse) Reset()         { *m = GetClientsResponse{} }
func (m *GetClientsResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientsResponse) ProtoMessage()    {}
func (*GetClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}

func (m *GetClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsResponse.Unmarshal(m, b)
}
func (m *GetClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsResponse.Marshal(b, m, deterministic)
}
func (m *GetClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsResponse.Merge(m, src)
}
func (m *GetClientsResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientsResponse.Size(m)
}
func (m *GetClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsResponse proto.InternalMessageInfo

func (m *GetClientsResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type CountTopicsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountTopicsRequest) Reset()         { *m = CountTopicsRequest{} }
func (m *CountTopicsRequest) String() string { return proto.CompactTextString(m) }
func (*CountTopicsRequest) ProtoMessage()    {}
func (*CountTopicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}

func (m *CountTopicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountTopicsRequest.Unmarshal(m, b)
}
func (m *CountTopicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountTopicsRequest.Marshal(b, m, deterministic)
}
func (m *CountTopicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountTopicsRequest.Merge(m, src)
}
func (m *CountTopicsRequest) XXX_Size() int {
	return xxx_messageInfo_CountTopicsRequest.Size(m)
}
func (m *CountTopicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountTopicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountTopicsRequest proto.InternalMessageInfo

type CountTopicsResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountTopicsResponse) Reset()         { *m = CountTopicsResponse{} }
func (m *CountTopicsResponse) String() string { return proto.CompactTextString(m) }
func (*CountTopicsResponse) ProtoMessage()    {}
func (*CountTopicsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}

func (m *CountTopicsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountTopicsResponse.Unmarshal(m, b)
}
func (m *CountTopicsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountTopicsResponse.Marshal(b, m, deterministic)
}
func (m *CountTopicsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountTopicsResponse.Merge(m, src)
}
func (m *CountTopicsResponse) XXX_Size() int {
	return xxx_messageInfo_CountTopicsResponse.Size(m)
}
func (m *CountTopicsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountTopicsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountTopicsResponse proto.InternalMessageInfo

func (m *CountTopicsResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetTopicsRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsRequest) Reset()         { *m = GetTopicsRequest{} }
func (m *GetTopicsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicsRequest) ProtoMessage()    {}
func (*GetTopicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{31}
}

func (m *GetTopicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsRequest.Unmarshal(m, b)
}
func (m *GetTopicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsRequest.Merge(m, src)
}
func (m *GetTopicsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicsRequest.Size(m)
}
func (m *GetTopicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsRequest proto.InternalMessageInfo

func (m *GetTopicsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetTopicsRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetTopicsResponse struct {
	Topics               []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsResponse) Reset()         { *m = GetTopicsResponse{} }
func (m *GetTopicsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTopicsResponse) ProtoMessage()    {}
func (*GetTopicsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{32}
}

func (m *GetTopicsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsResponse.Unmarshal(m, b)
}
func (m *GetTopicsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsResponse.Marshal(b, m, deterministic)
}
func (m *GetTopicsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsResponse.Merge(m, src)
}
func (m *GetTopicsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTopicsResponse.Size(m)
}
func (m *GetTopicsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsResponse proto.InternalMessageInfo

func (m *GetTopicsResponse) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type SendMessageRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{33}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{34}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Client)(nil), "pb.Client")
	proto.RegisterType((*NewClientRequest)(nil), "pb.NewClientRequest")
	proto.RegisterType((*NewClientResponse)(nil), "pb.NewClientResponse")
	proto.RegisterType((*RemoveClientRequest)(nil), "pb.RemoveClientRequest")
	proto.RegisterType((*RemoveClientResponse)(nil), "pb.RemoveClientResponse")
	proto.RegisterType((*NewTopicClientRequest)(nil), "pb.NewTopicClientRequest")
	proto.RegisterType((*NewTopicClientResponse)(nil), "pb.NewTopicClientResponse")
	proto.RegisterType((*RemoveTopicClientRequest)(nil), "pb.RemoveTopicClientRequest")
	proto.RegisterType((*RemoveTopicClientResponse)(nil), "pb.RemoveTopicClientResponse")
	proto.RegisterType((*ResetClientRequest)(nil), "pb.ResetClientRequest")
	proto.RegisterType((*ResetClientResponse)(nil), "pb.ResetClientResponse")
	proto.RegisterType((*NewTopicRequest)(nil), "pb.NewTopicRequest")
	proto.RegisterType((*NewTopicResponse)(nil), "pb.NewTopicResponse")
	proto.RegisterType((*RemoveTopicRequest)(nil), "pb.RemoveTopicRequest")
	proto.RegisterType((*RemoveTopicResponse)(nil), "pb.RemoveTopicResponse")
	proto.RegisterType((*NewClientKeyRequest)(nil), "pb.NewClientKeyRequest")
	proto.RegisterType((*NewClientKeyResponse)(nil), "pb.NewClientKeyResponse")
	proto.RegisterType((*CountTopicsForClientRequest)(nil), "pb.CountTopicsForClientRequest")
	proto.RegisterType((*CountTopicsForClientResponse)(nil), "pb.CountTopicsForClientResponse")
	proto.RegisterType((*GetTopicsForClientRequest)(nil), "pb.GetTopicsForClientRequest")
	proto.RegisterType((*GetTopicsForClientResponse)(nil), "pb.GetTopicsForClientResponse")
	proto.RegisterType((*CountClientsForTopicRequest)(nil), "pb.CountClientsForTopicRequest")
	proto.RegisterType((*CountClientsForTopicResponse)(nil), "pb.CountClientsForTopicResponse")
	proto.RegisterType((*GetClientsForTopicRequest)(nil), "pb.GetClientsForTopicRequest")
	proto.RegisterType((*GetClientsForTopicResponse)(nil), "pb.GetClientsForTopicResponse")
	proto.RegisterType((*CountClientsRequest)(nil), "pb.CountClientsRequest")
	proto.RegisterType((*CountClientsResponse)(nil), "pb.CountClientsResponse")
	proto.RegisterType((*GetClientsRequest)(nil), "pb.GetClientsRequest")
	proto.RegisterType((*GetClientsResponse)(nil), "pb.GetClientsResponse")
	proto.RegisterType((*CountTopicsRequest)(nil), "pb.CountTopicsRequest")
	proto.RegisterType((*CountTopicsResponse)(nil), "pb.CountTopicsResponse")
	proto.RegisterType((*GetTopicsRequest)(nil), "pb.GetTopicsRequest")
	proto.RegisterType((*GetTopicsResponse)(nil), "pb.GetTopicsResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "pb.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "pb.SendMessageResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 990 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x6d, 0x8f, 0xdb, 0x44,
	0x10, 0x96, 0x13, 0x48, 0x9b, 0x49, 0x68, 0x93, 0xc9, 0xfb, 0xde, 0xd1, 0xbb, 0x5a, 0x48, 0x3d,
	0xa5, 0xbd, 0xa4, 0x4d, 0x4f, 0x22, 0xcd, 0x27, 0xd2, 0xab, 0x00, 0x09, 0x28, 0xc5, 0x14, 0x54,
	0x24, 0x24, 0xe4, 0x4b, 0xb7, 0x51, 0xe0, 0x62, 0x9b, 0xb3, 0xdb, 0x53, 0x41, 0x7c, 0xe9, 0x4f,
	0x80, 0x9f, 0xc6, 0x5f, 0xe0, 0x5f, 0xf0, 0x05, 0x79, 0x76, 0xd7, 0xd9, 0xf5, 0x4b, 0x44, 0xa0,
	0x9f, 0xee, 0x3c, 0xbb, 0xf3, 0x3c, 0xcf, 0x3c, 0x1e, 0xcf, 0x28, 0x50, 0x75, 0x83, 0xd5, 0x28,
	0xb8, 0xf0, 0x23, 0x1f, 0x4b, 0xc1, 0x19, 0xdb, 0x5f, 0xfa, 0xfe, 0xf2, 0x9c, 0x8f, 0xdd, 0x60,
	0x35, 0x76, 0x3d, 0xcf, 0x8f, 0xdc, 0x68, 0xe5, 0x7b, 0xa1, 0xb8, 0xc1, 0xee, 0xd0, 0x9f, 0xc5,
	0xf1, 0x92, 0x7b, 0xc7, 0xe1, 0xa5, 0xbb, 0x5c, 0xf2, 0x8b, 0xb1, 0x1f, 0xd0, 0x8d, 0xec, 0x6d,
	0x7b, 0x1f, 0x2a, 0xa7, 0xe7, 0x2b, 0xee, 0x45, 0x88, 0xf0, 0x8e, 0xe7, 0xae, 0x79, 0xdf, 0x3a,
	0xb4, 0x8e, 0xaa, 0x0e, 0xfd, 0x6f, 0x7f, 0x0a, 0x8d, 0xc7, 0xfc, 0x52, 0x5c, 0x70, 0xf8, 0xcf,
	0x2f, 0x79, 0x18, 0xa1, 0x0d, 0x95, 0x05, 0x05, 0xe8, 0x66, 0x6d, 0x02, 0xa3, 0xe0, 0x6c, 0x24,
	0xaf, 0xc8, 0x13, 0x6c, 0x40, 0xf9, 0x27, 0xfe, 0xba, 0x5f, 0x3a, 0xb4, 0x8e, 0xea, 0x4e, 0xfc,
	0xaf, 0xdd, 0x82, 0xa6, 0x86, 0x14, 0x06, 0xbe, 0x17, 0x72, 0xfb, 0x01, 0xb4, 0x1c, 0xbe, 0xf6,
	0x5f, 0xf1, 0x9d, 0x19, 0xec, 0x2e, 0xb4, 0xcd, 0x54, 0x09, 0xf9, 0x15, 0x74, 0x1e, 0xf3, 0xcb,
	0xa7, 0x7e, 0xb0, 0x5a, 0xec, 0x2e, 0xbb, 0x0d, 0xef, 0x46, 0x71, 0x26, 0x09, 0xaf, 0x3a, 0xe2,
	0xc1, 0xee, 0x43, 0x37, 0x0d, 0x29, 0xc9, 0x9e, 0x42, 0x5f, 0x88, 0x78, 0xab, 0x7c, 0x7b, 0x30,
	0xc8, 0x41, 0x95, 0x94, 0x53, 0x40, 0x87, 0x87, 0x3c, 0xda, 0xdd, 0xb1, 0x4e, 0x6c, 0xb6, 0x96,
	0x29, 0x01, 0x6f, 0xc1, 0x75, 0x55, 0x9d, 0x42, 0x4b, 0x64, 0x59, 0xba, 0x2c, 0xa4, 0x5e, 0x90,
	0x17, 0x65, 0xf2, 0x30, 0x56, 0x93, 0x48, 0xdd, 0x9e, 0xdf, 0x51, 0x2f, 0xdb, 0x84, 0x78, 0x00,
	0xad, 0xa4, 0x31, 0x3e, 0xe3, 0xaf, 0x77, 0xec, 0x01, 0x33, 0x55, 0x42, 0xce, 0x61, 0xef, 0xd4,
	0x7f, 0xe9, 0x45, 0x44, 0x14, 0x7e, 0xec, 0x5f, 0xec, 0x6e, 0xd6, 0x09, 0xec, 0xe7, 0x43, 0x08,
	0x8a, 0xb8, 0xc4, 0x45, 0x7c, 0x4e, 0x10, 0x65, 0x47, 0x3c, 0xd8, 0x6b, 0x18, 0x7c, 0xc2, 0xff,
	0x07, 0x2d, 0x76, 0xa1, 0xe2, 0xbf, 0x78, 0x11, 0xf2, 0x88, 0x3a, 0xa2, 0xec, 0xc8, 0xa7, 0x0d,
	0x5d, 0x59, 0xa7, 0x3b, 0x01, 0x96, 0x47, 0x27, 0x25, 0x76, 0xa1, 0x42, 0xc6, 0x87, 0x7d, 0xeb,
	0xb0, 0x7c, 0x54, 0x75, 0xe4, 0x93, 0x7d, 0x5f, 0xba, 0x23, 0xae, 0xc7, 0x89, 0xff, 0xe2, 0xe5,
	0x29, 0x3f, 0x32, 0x49, 0x5b, 0xfd, 0xf8, 0x81, 0xfc, 0xd8, 0x85, 0x68, 0x47, 0x07, 0x1e, 0x92,
	0x03, 0x45, 0xa2, 0x3e, 0x80, 0x2b, 0xc2, 0x57, 0x61, 0x81, 0x69, 0xb9, 0x3a, 0x8a, 0xfb, 0x52,
	0x2f, 0x4d, 0xca, 0xb3, 0xef, 0x40, 0xdb, 0x0c, 0x6f, 0xad, 0x74, 0x0e, 0xcd, 0x8d, 0x10, 0x55,
	0xe1, 0xa6, 0x16, 0x2b, 0xbf, 0x96, 0x92, 0x0e, 0x31, 0x03, 0xd4, 0x21, 0x76, 0xaa, 0xa1, 0x0d,
	0xa8, 0xb5, 0xab, 0x2a, 0xe1, 0xb6, 0xac, 0x4c, 0x45, 0xb7, 0x56, 0xf0, 0x11, 0x34, 0x92, 0x66,
	0xfa, 0x6f, 0x05, 0xdc, 0x26, 0x0f, 0x52, 0x64, 0x45, 0x5d, 0xf8, 0x08, 0xf0, 0x6b, 0xee, 0x3d,
	0xff, 0x82, 0x87, 0xa1, 0xbb, 0xe4, 0xdb, 0x7b, 0xa2, 0x0f, 0x57, 0xd6, 0xe2, 0x9e, 0x1c, 0x94,
	0xea, 0x31, 0x7e, 0x77, 0x06, 0x8a, 0x20, 0x9d, 0xfc, 0x5d, 0x87, 0xd2, 0xe9, 0x04, 0xbf, 0x84,
	0x6a, 0x32, 0x1f, 0xb0, 0x1d, 0xfb, 0x96, 0x5e, 0x66, 0xac, 0x93, 0x8a, 0xca, 0x09, 0xd2, 0x79,
	0xf3, 0xe7, 0x5f, 0x7f, 0x94, 0xae, 0xdb, 0x30, 0xe6, 0x27, 0x63, 0x61, 0xf2, 0xcc, 0x1a, 0xe2,
	0x33, 0xa8, 0xeb, 0x4b, 0x07, 0x7b, 0x71, 0x76, 0xce, 0x06, 0x63, 0xfd, 0xec, 0x81, 0x89, 0x3c,
	0x4c, 0x21, 0x7f, 0x03, 0x35, 0x6d, 0x38, 0x63, 0x57, 0xe4, 0xa7, 0xe7, 0x3c, 0xeb, 0x65, 0xe2,
	0x26, 0x2c, 0xcb, 0x0a, 0xd6, 0x27, 0xa4, 0x10, 0x9c, 0x33, 0x6e, 0x85, 0xe0, 0xdc, 0x61, 0x2a,
	0x91, 0x27, 0x29, 0xe4, 0x27, 0x70, 0x55, 0x6d, 0x03, 0x6c, 0xc9, 0x64, 0xfd, 0xf3, 0x66, 0x6d,
	0x33, 0x28, 0xd1, 0x06, 0x84, 0xd6, 0xb2, 0x9b, 0x31, 0x1a, 0xbd, 0xdd, 0xf1, 0xaf, 0xf4, 0xe7,
	0x37, 0xfc, 0x2e, 0xb6, 0x20, 0xd9, 0x0f, 0xca, 0x82, 0xf4, 0x72, 0x61, 0xbd, 0x4c, 0xdc, 0x84,
	0x1e, 0xe6, 0x40, 0x3f, 0x87, 0x6b, 0xe6, 0x06, 0xc7, 0x81, 0xae, 0xce, 0xf4, 0x98, 0xe5, 0x1d,
	0x49, 0x8e, 0x3d, 0xe2, 0xe8, 0xb0, 0xc6, 0xc6, 0x0c, 0x41, 0x15, 0x5b, 0xb2, 0x86, 0x66, 0x66,
	0x6f, 0xe3, 0x7e, 0x4a, 0xae, 0xc9, 0xf5, 0x7e, 0xc1, 0xa9, 0x49, 0x37, 0xcc, 0xa5, 0xfb, 0x45,
	0x0e, 0xa8, 0xd4, 0xfc, 0xc7, 0x03, 0x1a, 0x10, 0xc5, 0xfb, 0x8f, 0x1d, 0x16, 0x5f, 0x90, 0xbc,
	0x07, 0xc4, 0x3b, 0xc0, 0x5e, 0x9a, 0x37, 0x1c, 0xd3, 0xa7, 0x8e, 0x1e, 0xcd, 0xaa, 0x34, 0x33,
	0x55, 0x53, 0xb8, 0x00, 0xd9, 0x8d, 0xa2, 0x63, 0xf3, 0x05, 0x62, 0x33, 0xc3, 0x8a, 0x6f, 0x2c,
	0x73, 0x1a, 0xab, 0x51, 0xaf, 0x15, 0x9b, 0xbf, 0x65, 0xb4, 0x62, 0x0b, 0xb6, 0x84, 0x7d, 0x8b,
	0x68, 0x6f, 0xe2, 0x41, 0xa6, 0x6f, 0xa4, 0x08, 0x55, 0xf4, 0x2b, 0x7d, 0x40, 0x27, 0x0a, 0x54,
	0xd1, 0x05, 0xfc, 0x37, 0x8a, 0x8e, 0x25, 0xfb, 0x4d, 0x62, 0xdf, 0xc3, 0x41, 0x21, 0x3b, 0x7e,
	0x0f, 0x75, 0xbd, 0x00, 0xf1, 0x11, 0xe7, 0xac, 0x2c, 0xf1, 0x11, 0xe7, 0x2d, 0xad, 0x3c, 0x6b,
	0x55, 0x55, 0x4f, 0x00, 0x36, 0xf2, 0xb0, 0x63, 0xca, 0x55, 0xc8, 0xdd, 0x74, 0x58, 0xe2, 0xb6,
	0x08, 0xf7, 0x3d, 0xac, 0x69, 0xb8, 0xf8, 0x0c, 0x6a, 0x5a, 0x77, 0x89, 0x0f, 0x39, 0xbb, 0x9d,
	0x58, 0x2f, 0x13, 0x97, 0xa0, 0x7d, 0x02, 0x45, 0x6c, 0x24, 0x96, 0x28, 0xad, 0x9f, 0x43, 0x35,
	0xe9, 0x1f, 0x31, 0xd0, 0xd3, 0x2b, 0x8b, 0x75, 0x52, 0x51, 0x89, 0x89, 0x84, 0x59, 0x47, 0xd8,
	0x60, 0xe2, 0xb7, 0x50, 0xd3, 0x96, 0x87, 0xd0, 0x99, 0xdd, 0x49, 0x42, 0x67, 0xce, 0x96, 0xb1,
	0xbb, 0x84, 0xd9, 0xb0, 0xa9, 0x78, 0xb9, 0x91, 0x66, 0xd6, 0xf0, 0xe1, 0xa3, 0xdf, 0xe7, 0x73,
	0xbc, 0x0a, 0x95, 0xc5, 0xe4, 0xd8, 0x0d, 0x56, 0xec, 0xda, 0xbd, 0xc9, 0x87, 0xa3, 0xbb, 0xa3,
	0xbb, 0xa3, 0x7b, 0xb3, 0xe9, 0x74, 0x3a, 0x1d, 0x5a, 0xa5, 0x49, 0xc3, 0x0d, 0x82, 0xf3, 0xd5,
	0x82, 0x7e, 0x88, 0x8d, 0x7f, 0x0c, 0x7d, 0x6f, 0x96, 0x89, 0x9c, 0x55, 0xe8, 0xf7, 0xd9, 0xfd,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x03, 0x23, 0x1f, 0xfc, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// C2Client is the client API for C2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type C2Client interface {
	// Create a new client
	NewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error)
	// Remove a client
	RemoveClient(ctx context.Context, in *RemoveClientRequest, opts ...grpc.CallOption) (*RemoveClientResponse, error)
	// Instruct the C2 server to send a reset command to the client
	ResetClient(ctx context.Context, in *ResetClientRequest, opts ...grpc.CallOption) (*ResetClientResponse, error)
	// Generate a new key for the client
	NewClientKey(ctx context.Context, in *NewClientKeyRequest, opts ...grpc.CallOption) (*NewClientKeyResponse, error)
	// Create a new topic
	NewTopic(ctx context.Context, in *NewTopicRequest, opts ...grpc.CallOption) (*NewTopicResponse, error)
	// Remove a topic
	RemoveTopic(ctx context.Context, in *RemoveTopicRequest, opts ...grpc.CallOption) (*RemoveTopicResponse, error)
	// Associate a topic with a client
	NewTopicClient(ctx context.Context, in *NewTopicClientRequest, opts ...grpc.CallOption) (*NewTopicClientResponse, error)
	// Remove a topic / client association
	RemoveTopicClient(ctx context.Context, in *RemoveTopicClientRequest, opts ...grpc.CallOption) (*RemoveTopicClientResponse, error)
	// Count the number of topics for a client
	CountTopicsForClient(ctx context.Context, in *CountTopicsForClientRequest, opts ...grpc.CallOption) (*CountTopicsForClientResponse, error)
	// Retrieve paginated topics for a client
	GetTopicsForClient(ctx context.Context, in *GetTopicsForClientRequest, opts ...grpc.CallOption) (*GetTopicsForClientResponse, error)
	// Count the number of clients for a topic
	CountClientsForTopic(ctx context.Context, in *CountClientsForTopicRequest, opts ...grpc.CallOption) (*CountClientsForTopicResponse, error)
	// Retrieve paginated clients for a topic
	GetClientsForTopic(ctx context.Context, in *GetClientsForTopicRequest, opts ...grpc.CallOption) (*GetClientsForTopicResponse, error)
	// Count the number of clients
	CountClients(ctx context.Context, in *CountClientsRequest, opts ...grpc.CallOption) (*CountClientsResponse, error)
	// Retrieve paginated clients
	GetClients(ctx context.Context, in *GetClientsRequest, opts ...grpc.CallOption) (*GetClientsResponse, error)
	// Count the number of topics
	CountTopics(ctx context.Context, in *CountTopicsRequest, opts ...grpc.CallOption) (*CountTopicsResponse, error)
	// Retrieve paginated topics
	GetTopics(ctx context.Context, in *GetTopicsRequest, opts ...grpc.CallOption) (*GetTopicsResponse, error)
	// Send a message on a topic
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type c2Client struct {
	cc *grpc.ClientConn
}

func NewC2Client(cc *grpc.ClientConn) C2Client {
	return &c2Client{cc}
}

func (c *c2Client) NewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error) {
	out := new(NewClientResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/NewClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) RemoveClient(ctx context.Context, in *RemoveClientRequest, opts ...grpc.CallOption) (*RemoveClientResponse, error) {
	out := new(RemoveClientResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/RemoveClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) ResetClient(ctx context.Context, in *ResetClientRequest, opts ...grpc.CallOption) (*ResetClientResponse, error) {
	out := new(ResetClientResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/ResetClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) NewClientKey(ctx context.Context, in *NewClientKeyRequest, opts ...grpc.CallOption) (*NewClientKeyResponse, error) {
	out := new(NewClientKeyResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/NewClientKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) NewTopic(ctx context.Context, in *NewTopicRequest, opts ...grpc.CallOption) (*NewTopicResponse, error) {
	out := new(NewTopicResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/NewTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) RemoveTopic(ctx context.Context, in *RemoveTopicRequest, opts ...grpc.CallOption) (*RemoveTopicResponse, error) {
	out := new(RemoveTopicResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/RemoveTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) NewTopicClient(ctx context.Context, in *NewTopicClientRequest, opts ...grpc.CallOption) (*NewTopicClientResponse, error) {
	out := new(NewTopicClientResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/NewTopicClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) RemoveTopicClient(ctx context.Context, in *RemoveTopicClientRequest, opts ...grpc.CallOption) (*RemoveTopicClientResponse, error) {
	out := new(RemoveTopicClientResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/RemoveTopicClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) CountTopicsForClient(ctx context.Context, in *CountTopicsForClientRequest, opts ...grpc.CallOption) (*CountTopicsForClientResponse, error) {
	out := new(CountTopicsForClientResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/CountTopicsForClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) GetTopicsForClient(ctx context.Context, in *GetTopicsForClientRequest, opts ...grpc.CallOption) (*GetTopicsForClientResponse, error) {
	out := new(GetTopicsForClientResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/GetTopicsForClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) CountClientsForTopic(ctx context.Context, in *CountClientsForTopicRequest, opts ...grpc.CallOption) (*CountClientsForTopicResponse, error) {
	out := new(CountClientsForTopicResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/CountClientsForTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) GetClientsForTopic(ctx context.Context, in *GetClientsForTopicRequest, opts ...grpc.CallOption) (*GetClientsForTopicResponse, error) {
	out := new(GetClientsForTopicResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/GetClientsForTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) CountClients(ctx context.Context, in *CountClientsRequest, opts ...grpc.CallOption) (*CountClientsResponse, error) {
	out := new(CountClientsResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/CountClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) GetClients(ctx context.Context, in *GetClientsRequest, opts ...grpc.CallOption) (*GetClientsResponse, error) {
	out := new(GetClientsResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/GetClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) CountTopics(ctx context.Context, in *CountTopicsRequest, opts ...grpc.CallOption) (*CountTopicsResponse, error) {
	out := new(CountTopicsResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/CountTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) GetTopics(ctx context.Context, in *GetTopicsRequest, opts ...grpc.CallOption) (*GetTopicsResponse, error) {
	out := new(GetTopicsResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/GetTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/pb.C2/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// C2Server is the server API for C2 service.
type C2Server interface {
	// Create a new client
	NewClient(context.Context, *NewClientRequest) (*NewClientResponse, error)
	// Remove a client
	RemoveClient(context.Context, *RemoveClientRequest) (*RemoveClientResponse, error)
	// Instruct the C2 server to send a reset command to the client
	ResetClient(context.Context, *ResetClientRequest) (*ResetClientResponse, error)
	// Generate a new key for the client
	NewClientKey(context.Context, *NewClientKeyRequest) (*NewClientKeyResponse, error)
	// Create a new topic
	NewTopic(context.Context, *NewTopicRequest) (*NewTopicResponse, error)
	// Remove a topic
	RemoveTopic(context.Context, *RemoveTopicRequest) (*RemoveTopicResponse, error)
	// Associate a topic with a client
	NewTopicClient(context.Context, *NewTopicClientRequest) (*NewTopicClientResponse, error)
	// Remove a topic / client association
	RemoveTopicClient(context.Context, *RemoveTopicClientRequest) (*RemoveTopicClientResponse, error)
	// Count the number of topics for a client
	CountTopicsForClient(context.Context, *CountTopicsForClientRequest) (*CountTopicsForClientResponse, error)
	// Retrieve paginated topics for a client
	GetTopicsForClient(context.Context, *GetTopicsForClientRequest) (*GetTopicsForClientResponse, error)
	// Count the number of clients for a topic
	CountClientsForTopic(context.Context, *CountClientsForTopicRequest) (*CountClientsForTopicResponse, error)
	// Retrieve paginated clients for a topic
	GetClientsForTopic(context.Context, *GetClientsForTopicRequest) (*GetClientsForTopicResponse, error)
	// Count the number of clients
	CountClients(context.Context, *CountClientsRequest) (*CountClientsResponse, error)
	// Retrieve paginated clients
	GetClients(context.Context, *GetClientsRequest) (*GetClientsResponse, error)
	// Count the number of topics
	CountTopics(context.Context, *CountTopicsRequest) (*CountTopicsResponse, error)
	// Retrieve paginated topics
	GetTopics(context.Context, *GetTopicsRequest) (*GetTopicsResponse, error)
	// Send a message on a topic
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
}

// UnimplementedC2Server can be embedded to have forward compatible implementations.
type UnimplementedC2Server struct {
}

func (*UnimplementedC2Server) NewClient(ctx context.Context, req *NewClientRequest) (*NewClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewClient not implemented")
}
func (*UnimplementedC2Server) RemoveClient(ctx context.Context, req *RemoveClientRequest) (*RemoveClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveClient not implemented")
}
func (*UnimplementedC2Server) ResetClient(ctx context.Context, req *ResetClientRequest) (*ResetClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetClient not implemented")
}
func (*UnimplementedC2Server) NewClientKey(ctx context.Context, req *NewClientKeyRequest) (*NewClientKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewClientKey not implemented")
}
func (*UnimplementedC2Server) NewTopic(ctx context.Context, req *NewTopicRequest) (*NewTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTopic not implemented")
}
func (*UnimplementedC2Server) RemoveTopic(ctx context.Context, req *RemoveTopicRequest) (*RemoveTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTopic not implemented")
}
func (*UnimplementedC2Server) NewTopicClient(ctx context.Context, req *NewTopicClientRequest) (*NewTopicClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTopicClient not implemented")
}
func (*UnimplementedC2Server) RemoveTopicClient(ctx context.Context, req *RemoveTopicClientRequest) (*RemoveTopicClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTopicClient not implemented")
}
func (*UnimplementedC2Server) CountTopicsForClient(ctx context.Context, req *CountTopicsForClientRequest) (*CountTopicsForClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountTopicsForClient not implemented")
}
func (*UnimplementedC2Server) GetTopicsForClient(ctx context.Context, req *GetTopicsForClientRequest) (*GetTopicsForClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicsForClient not implemented")
}
func (*UnimplementedC2Server) CountClientsForTopic(ctx context.Context, req *CountClientsForTopicRequest) (*CountClientsForTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountClientsForTopic not implemented")
}
func (*UnimplementedC2Server) GetClientsForTopic(ctx context.Context, req *GetClientsForTopicRequest) (*GetClientsForTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientsForTopic not implemented")
}
func (*UnimplementedC2Server) CountClients(ctx context.Context, req *CountClientsRequest) (*CountClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountClients not implemented")
}
func (*UnimplementedC2Server) GetClients(ctx context.Context, req *GetClientsRequest) (*GetClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}
func (*UnimplementedC2Server) CountTopics(ctx context.Context, req *CountTopicsRequest) (*CountTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountTopics not implemented")
}
func (*UnimplementedC2Server) GetTopics(ctx context.Context, req *GetTopicsRequest) (*GetTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopics not implemented")
}
func (*UnimplementedC2Server) SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterC2Server(s *grpc.Server, srv C2Server) {
	s.RegisterService(&_C2_serviceDesc, srv)
}

func _C2_NewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).NewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/NewClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).NewClient(ctx, req.(*NewClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_RemoveClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).RemoveClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/RemoveClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).RemoveClient(ctx, req.(*RemoveClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_ResetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).ResetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/ResetClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).ResetClient(ctx, req.(*ResetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_NewClientKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).NewClientKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/NewClientKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).NewClientKey(ctx, req.(*NewClientKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_NewTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).NewTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/NewTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).NewTopic(ctx, req.(*NewTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_RemoveTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).RemoveTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/RemoveTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).RemoveTopic(ctx, req.(*RemoveTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_NewTopicClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTopicClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).NewTopicClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/NewTopicClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).NewTopicClient(ctx, req.(*NewTopicClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_RemoveTopicClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTopicClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).RemoveTopicClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/RemoveTopicClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).RemoveTopicClient(ctx, req.(*RemoveTopicClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_CountTopicsForClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountTopicsForClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).CountTopicsForClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/CountTopicsForClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).CountTopicsForClient(ctx, req.(*CountTopicsForClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_GetTopicsForClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicsForClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).GetTopicsForClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/GetTopicsForClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).GetTopicsForClient(ctx, req.(*GetTopicsForClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_CountClientsForTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountClientsForTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).CountClientsForTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/CountClientsForTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).CountClientsForTopic(ctx, req.(*CountClientsForTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_GetClientsForTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientsForTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).GetClientsForTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/GetClientsForTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).GetClientsForTopic(ctx, req.(*GetClientsForTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_CountClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).CountClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/CountClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).CountClients(ctx, req.(*CountClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/GetClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).GetClients(ctx, req.(*GetClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_CountTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).CountTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/CountTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).CountTopics(ctx, req.(*CountTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_GetTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).GetTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/GetTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).GetTopics(ctx, req.(*GetTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.C2/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _C2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.C2",
	HandlerType: (*C2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewClient",
			Handler:    _C2_NewClient_Handler,
		},
		{
			MethodName: "RemoveClient",
			Handler:    _C2_RemoveClient_Handler,
		},
		{
			MethodName: "ResetClient",
			Handler:    _C2_ResetClient_Handler,
		},
		{
			MethodName: "NewClientKey",
			Handler:    _C2_NewClientKey_Handler,
		},
		{
			MethodName: "NewTopic",
			Handler:    _C2_NewTopic_Handler,
		},
		{
			MethodName: "RemoveTopic",
			Handler:    _C2_RemoveTopic_Handler,
		},
		{
			MethodName: "NewTopicClient",
			Handler:    _C2_NewTopicClient_Handler,
		},
		{
			MethodName: "RemoveTopicClient",
			Handler:    _C2_RemoveTopicClient_Handler,
		},
		{
			MethodName: "CountTopicsForClient",
			Handler:    _C2_CountTopicsForClient_Handler,
		},
		{
			MethodName: "GetTopicsForClient",
			Handler:    _C2_GetTopicsForClient_Handler,
		},
		{
			MethodName: "CountClientsForTopic",
			Handler:    _C2_CountClientsForTopic_Handler,
		},
		{
			MethodName: "GetClientsForTopic",
			Handler:    _C2_GetClientsForTopic_Handler,
		},
		{
			MethodName: "CountClients",
			Handler:    _C2_CountClients_Handler,
		},
		{
			MethodName: "GetClients",
			Handler:    _C2_GetClients_Handler,
		},
		{
			MethodName: "CountTopics",
			Handler:    _C2_CountTopics_Handler,
		},
		{
			MethodName: "GetTopics",
			Handler:    _C2_GetTopics_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _C2_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
